<?php

use Drupal\file\Entity\File;

/**
 * Implements hook_preprocess_region().
 *
 * Add header text from variable.
 *
 * @param $variables
 */
function ereolen_campaign_preprocess_region__header(&$variables) {
  $config = \Drupal::getContainer()->get('itk_hero.config')->getAll();

  // Fetch header top file.
  $file = isset($config['itk_header_image']) ? File::load($config['itk_header_image']) : FALSE;
  $variables['header_image'] = $file ? $file->url() : '';
}